spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: (username)
      password: (password)
      database: (database)
      authentication-database: admin

discord:
  token: (token)
  owner: (bot owner discord id)
  default-voice-channel: (channel id)
  advertise-channel: (channel id)
